import { useState, useEffect } from "react";
import { Heart, Waves } from "lucide-react";
import { VitalSignCard } from "@/components/VitalSignCard";
import { WebcamFeed } from "@/components/WebcamFeed";
import { VitalSignsChart } from "@/components/VitalSignsChart";
import { VitalDataPoint } from "@/components/VitalDataPoint";
import { NoteSummary } from "@/components/NoteSummary";

const Index = () => {
  const [heartRate, setHeartRate] = useState(72);
  const [breathingRate, setBreathingRate] = useState(16);
  const [vitalHistory, setVitalHistory] = useState<VitalDataPoint[]>([]);

  /* ------------------ SIMULATED REAL-TIME DATA ------------------ */
  useEffect(() => {
    const interval = setInterval(() => {
      setHeartRate((prev) => Math.max(55, Math.min(150, prev + (Math.random() - 0.5) * 10)));
      setBreathingRate((prev) => Math.max(10, Math.min(30, prev + (Math.random() - 0.5) * 4)));
    }, 2000);

    return () => clearInterval(interval);
  }, []);

  /* ------------------ RECORD VITAL HISTORY ------------------ */
  useEffect(() => {
    const newPoint: VitalDataPoint = {
      timestamp: Date.now(),
      time: new Date().toLocaleTimeString([], {
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit",
      }),
      heartRate: Math.round(heartRate),
      breathingRate: Math.round(breathingRate),
    };

    setVitalHistory((prev) => [...prev, newPoint].slice(-120));
  }, [heartRate, breathingRate]);

  return (
    <div className="min-h-screen bg-black p-4">
      <div className="max-w-7xl mx-auto space-y-6">

        {/* ------------------ CAMERA + STATUS BOX ------------------ */}
        <div className="flex flex-row gap-4">
          <WebcamFeed />
          <NoteSummary text={"This is a summary generated by the LLM. Replace with your actual summary text."} />
        </div>
        <div className="flex flex-row gap-4">
          <VitalSignCard
            title="Heart Rate"
            value={Math.round(heartRate)}
            unit="BPM"
            icon={Heart}
            status={heartRate < 60 || heartRate > 110 ? "critical" : "normal"}
            subtitle="Normal: 60-100"
            chartData={vitalHistory.slice(-10).map((d) => ({ value: d.heartRate }))}
          />
          <VitalSignCard
            title="Breathing Rate"
            value={Math.round(breathingRate)}
            unit="BrPM"
            icon={Waves}
            status={breathingRate < 12 || breathingRate > 20 ? "critical" : "normal"}
            subtitle="Normal: 12-20"
            chartData={vitalHistory.slice(-10).map((d) => ({ value: d.breathingRate }))}
          />
        </div>
        {/* ------------------ GRAPH SECTION ------------------ */}
        <VitalSignsChart data={vitalHistory} />
      </div>
    </div>
  );
};

export default Index;
